apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postmark-relay-mapping
  namespace: pp-postmark-relay
spec:
  encryptedData:
    mapping.json: AgA9qRhnClJmnD3SnvopUNFFBP69+8e00eiU+zzFROXzdRzEiczTYjRo1wdh51hURUummlGCsHqDD3QDOKBiogtKJ0eqn+mhoPES+6etpb4RQ2a74WfpiP6SAzvzb4VhI3y25MiTxVlcTh6+q0+dXD219tsS+N5pgN8d1D2MUpwM1JBxizSoxippvxIxD3lrWmAS4wHE79ZLol9P5Zns4xf4u7Mjrxj5UMYshH5ef8jk+dV60nVLk21ZlsXzrHjPeiJI3nOByWVUkzbcujpPGb1HhjK/Ugk8/kInrKLhw0S/laZQH59o0fxtu7fap1M5XMH6mKoh5u67kaQK0hu326IGd9Plk4vhdRFbnuygVkg2LkZd3J7DfwWn8/w+LMMm5rU8HO/wMcep0JBVw6jgPCt2PtTvbs4ymWxHV8mc6EcTyf7gPheXf9eBH30rZuPfwBTgjxkoz/81Gst8LV1c4mGuWsVk571gfAdWI+2PQsLB34AlRo6dOrNgIC3+GiXe2Dye4HlLtWANIdcgLB9Vnp9HVQtg0HN852Diea9tNDOSwEKiWignzxd2BWYrY7rifYgW2evF+83qthyvC21nU8PqPdpJ4vLWtAINGAGpTTSVmUCVcbd5SeWyMlWxTPh4pm2D/VatRODfKjX+Ylru6CXhcuOJqdhB4EAodOovqf0EoU/Bwrq1rylyVrAZdlfZtft3WyPaU/Dht0mMyY7ZIXv8H459/uMv1c1hHiXyth/pJWKpJgflcnPIP/WjqlxO1YaNcs1c4w70ZgHexSVZ7plhERNX6j2R0cxxQOBf/Js5SmaVb6mnUQ==
  template:
    metadata:
      creationTimestamp: null
      name: postmark-relay-mapping
      namespace: pp-postmark-relay
    type: Opaque
