apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    GF_DATABASE_PASSWORD: AgBwOTeCdEcFgQBXloBFW6w9kpJ320BlkCv2FGxglBPiOozyTd7xnT+Ewxknk+oe3dBV6K11Wh8FKF1Rd+DRmBY/rzH/GS0xMYd2FFt43MuGsKzJfVLuZ7Yjwp6SLv7IYCRCxOyD0XB3jxkubffNVIA/GsZ4HkUJJCCf/HMWglESx6pGUwhZeCXiMpZVd+CkcbUHz3EXd4NiLZFRTnzTM4P3gGgQWpicuiwjOfE1sYB8+B43i5/d/m1rVlBkJbUGBdi/P9JuEFUh0gvbtN40vzM8SNc/nQY2kaFy5kjQRB8Xm+2XljPf3n/hQB/V46N3lpsJUEtXkUeK3T09koJbE42+d/TiJ9sDLjPZrB8/sZ/9jyhcYjY1mm0/pLkyeH56JWCFHDIKO4jLDRBbx7MOaOTmMPnQ2nyBxyEj4fgvai6ZPtCZl8nkKZOVFtTKerD8gXwIwP3a36yh/VM/f95t/uVgJjke49kZnp4yfztJgp7/YOWlN0GH1sASrdwVdyub1NxTgTwRn+6ZAjgd6O8UcarYXsANjUB0CquH0wwApYFF5dM3loyZqdS5CumfSow56k9hdO87ytF3UzPIi+rHVCAMCdkLhkzONiNzP+dZLnQ6Mx+VRYqUWC3cELXGLNmi3I/AoqUMPa5OAHuvcYLRM7tAWYZtNHQFZ7Jf56IF/MPt3NZulwhVx7dnXAa5tyUjqK5baMGQ7TN2YIPutT2vnkok2PknK6FLY9ImoNuFZgGrBA==
    GF_DATABASE_USER: AgBqvqdk0Vvn7jzU/yudX5XSvjkB4KSLIEzaNFw7NcFcW5jaleBRkrRAhW53CzC5bkvofiqQo19rZ26lfwL5zILSVhVCx7pgiWR/ug0J3LuZ7UFzuwqFbHJxbv2MgRkuXhoY7OCAEM94LiQs2X3CJt0YIv9YKpRkn/ltyfRIgPj6NFPZYvtoq2HTm0H5dWgVMgiNT9YDRnJbyhNayHFmGP2O6AGruZH6utcLfXMNZw1VuYGHgM35xA40FAHooaJYhjpyTItfYCNCSD6EBHSOUr4uspiy60mg9/roclZKbPkq5eyBhUHqqCwEKppmsGeHXme4p07So9cN06qIuyOWZ6VnNREwew+Cp4fEssHuWBdp0zDADORz5AbW77ek7BEzm0ZYzh1eDf4RJQURGpm4HEWn0qslpF7qqG0QLBcxa3CBpzxF6hN2RmZyGjxpdM9qjk8MFIKeFPUD4V/WoGnZPwqqofkKT3cOAMFaB+FqP1IHtT4XARYGJcyr+7Y4OrSnqzALxoICo8FuEbu/u/BTwvd/L89ctsmOVnPauFPJ4eHgiTBX5QhlrfGAgRchYtdDxYtT83ndWUTTiRy3pQA466+T5wqV29TORU7rtY3s0vxBfizW4zdcToP44uAUwe1uJstlI5/sNmkLUhVPHbe15xh+XhhApJkjZOJJ6zDZjGNrlY9VyeQSAvVp3o1QLDXrxmI+ezgWloCN
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: monitoring
    type: Opaque
