apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    GF_DATABASE_PASSWORD: AgBc1ZCOGNur2ryWanJun6PsKCy7MgGzy1Ca2tzIGNb90E4kWldi7Pz7ZgI2kGvVny1UEa6M8UEH6AMJrUl0TBHbgT5BzvvrAf0HuTLgHwugY4WgBTjCvvbm0mx3hMWUmTGhTqkHZg8YUYsciHNKaTwJSXgZvNw3fWn6+G0pzhWzWGD+Ounoep+jB5PejKiRja6DfgT19SNN9lCBTzi53Zr+Ps0Wll/X1IJcFcwIvNOUPMQcJJafej9n3QARhlGdp3+J+iB/yiknVXKlVmOBghkO43ygPckl23EeJ+jPTPxHTG7PXzdm0mI2PwqPAb7lnjBHRgiGW/yra2kt7qFi5Ykdvbfmbk+81S0dtzLmUsTPk+BHzW/CE/Bijp6GvbVvgczQlKeXivnGPiNkHkGDr9vVTjH/FV/1U9JLNB4y3VOI8OVeveOiPvxuwViHVA9IHpN5IBh0plDe45KBwQ9rYXROy5UIm4AVpMTD+mLazNuf8z3LTEnW1VNUSXn1qzDz+6WKVAGZSIkfDIRQneQi+WeW4uqA4+J0Hnwpu6VKBuDkNe35E7JsK8TYMUBBoJLr66OUXupk7tbPLbi75Nc+7aqX7SQ1vTzlZGMpTXKrEUe8PfrVNMMsCuY3M4k7XChIY4tM1b2nP2pGbQtGQ6YEy/LJjbDQ/5fX0eQhDK76OLp0tYtNAle68JcJO087SG88t7KmcpqzauAARAXPa1TJvgJeC9LZkHIh5skzNHpKTmmUjQ==
    GF_DATABASE_USER: AgAceQesSwgTXEigLKQkXt6cPRTuTfLEYKsX3z3fc0r2Nlfl0qCK6mEA8sPAn31hoAg2aVadUtiLG+vFjzwuMJl5ZeUI/kDq4oxcwn3Oqf0885NC4gThwdh9QT+lc3NPeGtVEgBeIcTl6nuO0iY7O1CjiaZrtDC+u1nAAayQo9zwc+JxVdVBh3jSnZqG2xqcQv592JjE4wtjgq7IpB/3Fs+02ELiKPjMxsLZKit5laQs82LCC0LAupDS0dhTOnI64kMdd5aEJlw/NWwegMAiSFMytfcaPZkeEHSwhoUT7qrimVuemmhEq/0TpZK7f3tCe1OeopU9bigDj/Iiof7FNcS8GL3fAS5Z8h8kuefxK29DNL7qFwWZTYDhL7riQ35qcXpvqW37N+cmBD7Hm0CplkBnLt4IFn+GsYHInqhdGtY7LRqp0X+YgVb1WyGxiAswgt1rpT3tDJ/TjWilYus3iq9BTirsR/r2jl37Y6kX39MmeW9i1hIjNm8koNA79HYSXqiYqH2aT9yCdleAzdlW1R7SPp2A11dTnO2ucMFq1vNmP3H4zPME15ZESIsIRMMSybKdmXjzsgha7XxbUnQl2Jzbs+oNPv3R6U1vwCbH351H8VcxxM7eI7NGeeKMjdTbDoXM2BLiyKxdCk63SsKZW/7PDEOrcMej6LMMQF5dD+u0KUTdEEqxrrIQPMPdrd/MICQzfcXfRfsH
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: monitoring
    type: Opaque
