apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config-file
  namespace: monitoring
data:
  telegraf.conf: |+
    [agent]
      interval = "1s"
      round_interval = true
      metric_batch_size = 100
      metric_buffer_limit = 10000
      collection_jitter = "500ms"
      flush_interval = "5s"
      flush_jitter = "0s"
      precision = "500ms"
      quiet = true
      omit_hostname = true

    [[outputs.influxdb_v2]]
      urls = ["https://moondancer.db.local:8086"]
      token = "$INFLUXDB_TOKEN"
      organization = "marcsello-corp"
      bucket = "monitoring"
      timeout = "30s"
      user_agent = "telegraf"

      tls_ca = "/etc/ssl/certs/local.crt"

    [[inputs.http_listener_v2]]
      service_address = ":8000"
      paths = ["/telegraf"]
      methods = ["POST", "PUT"]
      read_timeout = "10s"
      write_timeout = "10s"
      data_source = "body"
      data_format = "influx"

      basic_username = "proxy"
      basic_password = "$TELEGRAF_PROXY_PASSWORD"
