apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ttaproxy-htpasswd
  namespace: monitoring
spec:
  encryptedData:
    .htpasswd: AgCGCYvgPDTmbzqm/cdvOze7xm2z5PbpwWY1goMSLqGY1yY1aqQfXNzGRS+MrYQLSetuzzKSFx62NU4/tOpJsZu4LGptKv5LMqiAegBnZDsTMgQWCLpiRZByRmr5Dt6btmltCwkkq58XEtAjHJKvKI16W6r2pb1GWtzKMtpt04E59gda3eCwFAkpTgO4bZWC8KE/7SiXZGuVmJXLjcolKf3v7ynkmkoPlOv2XVCGqFV4LBW/o+MJ4yMq32fNEAusGkqTPLQm9x146rLV9J5PE9Ks9x+MrhNm/DihZ0vZ0/lLUlPv8MBvTGMARSi06Xy6Qp0z39+w4B3KRN5Qa2YY+sceWeB68r+AD0HgGzTZjR1x47Z4LphGUFfR9Inw68X4z+OnZv7SW/RH4cT0ZY5GP5BoQ0RZ7qhuvJvX/2G4E+DNQEPoitxl+jv889VsYDtWUyz9S/Nwk7oYfS1/Qt7bbU0/kfH3odrRpTDiTSuIgZ9/J4EXSLJy264Qm7ceZevZWdT9PYVmJV+2BM1nhXEV3dUVmTMSOcw8b6CNq6XEckGwd8G+Ofswdpwmy6ZlFNclr9Txf6MpSwLQ5PDwsLvvLGi0jT8tcgQN3GabCds6rQmroeaZN0Sz//fhL5j2uTEbhdhqI/vXsEwZMzVmu8V/goBZ1Cl9MlriRQ/crpaus6yIrsDVdDbWj1SxukjsRqshc9mGd2UhTqUkkofxX/uoneE2lAHHITHEybO/XXNtjNcpl8Xa7kPLclTKscTpdXTo2Fa/sCwgrvCJbdypnhp+w+ZNbRzYedhB6gte0nN0xj4A2oY6fp6zggvkNYTxM+CFTOUR8a0SGtK1jjv4yQYk/JLklKj5cyYpUWFPWM2+TwBdFcqpIle1du9k6nstiHe+ZmhqVLVRbCtOGc3GEcFddSAc8FSbKzr92e+UMpTSf6gyQfN4oQoPyffKgdeC3BfNI4c5R+UsTHyVRkWbBPOn3gsOShzKxjCgaVKqMAxaDQiYCQ6U7LfSpr2vikKHjcewgyclemzfCM1euVRJQfOlskFyz/SnmWNqQyt0yXOU82QQeKECxX7nSu2tAPdeQAJiCEHYIMhKFPD/+cyDEsMCg474JbW/tb2ZUuj2H3qN1Rdt7yq37gJkUA6JG71UD88ohK+N1iLe6lTUGOh0+5JhcUzoDG1QpmdG3iIsWvVHy2CjDqNUp8hDhkMostUrbERXd3UE5w+Y7ZbORF7dnfiHn3hOEnMb+t2LxydJqdl12nYVvJUL1cdOL6fSmhivK5nzCBQT+EiuWQ8HEU1AhxP+FapBvRINNCUAKEUaL8onnzBYj0smvOr/kv8vfihSjzHwUDGDIU08IMvQRuq5MBZD5r5csoXZGw7zN1moa0uSDvIsP9KmUky0x9WUGbsOqHsthlquzdRBdb9Iw3b75YxlIad0yWkZ1A5144iokHGk4Rhb2/cTG/NKwvPE8JkpB6yzgP1rSWuYFbiMrfeW1IgpreC13wjb1nyaYxipL+WPEoS2xgnLeP10AJxr5RtKEJBWiySfZjKLfbjxcEyO4smQiQ==
  template:
    metadata:
      creationTimestamp: null
      name: ttaproxy-htpasswd
      namespace: monitoring
    type: Opaque
