apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ttaproxy-htpasswd
  namespace: monitoring
spec:
  encryptedData:
    .htpasswd: AgBlLoe/pp2jhzawN6EsT36nIiQMQb5Wj4k47fJmjfbsXv/m0o/CUWA73Xf/VTflX+1iSYq3x5Xsq5PD6XBen3iAXF/3hOWxJ942pOw9o5wMlhyLlraEPR6j//44fHju6t23okDjgaGdWN5O7J4zGZ+BforAcergjRFe6sWPu4z0b6wenU73pXj57sXOxkyRHbMpYoJqgM/jpBvWzDB5DtdLs/pMtzsjYn+GDlSKfpeL+Qy5iWW5Wk3umv7K2QCW9A9pvuRIKVNB6xa1EMoyMOxPA3MoHvf7Ox6lg56x8n+mGlw4Y2F4cYS5IdbDWx/iwqPL4QcW93J8Looeb0kZotq17pZSKw0fSQLfeLSMswayeLgDanDsQ2158s9vWe231/TgvcnoSgesPqQn2xjqV/aXWrICK6Si3IDMmNHXwBIlw4IAwcBHa/jxq0q5+QWKp+XuxQE14EbEoA6sxkg+cWnLwSwMkgZR5sDwma4dmU+5I4e+nICaAeVH5JRzKBzRJsCrUyUkodGC8B8QXUps2zdzloL1pwN/oIcVN2K5Znw1f5iDMbE2jPHg1vrtOfZ6SpsMpPeQy16NuAxAREGUpNIxpzgaSerQuU5QHzduht3n+ykFHia3QCcSb1ktnD35MGOrDnakc8+McHOq83LH+Smy4MSsF0VgmNmSyTnheuUfiPU3pAhDtpg4SKJdzBj/bjN2x7YKWXUiWuH20xWaoNVOBeFTpXpxemO5PPdxlXBHBvjDxgrPo3RRDoMJbjIqSrO15laIJfocp5VZTxxsMTdGYej5MaT06OCUofPEAhFsEzRyaDcKyvOIOBUBCszcbIjuvCPU92M3L9T8PJyyypUpF0n563/ySFhlCDzRH9dhQAXuOP4DqtVsX7mNGVd+Qtg9fVorJwmwWHVUVt8SqJHhhSREPWFXthny8vJ3Ty8ZeSjxvkmmM93reJuSekjhnYxMEWmWXXleKNqxtVg2Eo+vIociXc16kPgQdejdA2C44/+aTpr//d0u+c+bIZ6PWOZo9Fnj2xz6u3gtYOWlEHUY6MqUONS3ZHTRDCLvlnflScGya1MfgGhL3p2Eg+Jan7hoC7jfGWe0u71eCWUp3faDUNfjE2N/hp1M+Hk0dgDRr3H6xdtB5SwrP2FRJMKSxNWVk5HzS214nN0z3jC7zxPZVY/ZC0RtwZLAJ3kLLuEFTPH6DBcStCFfQ0aZIWSPR3c9+o4tBoYD7Gyq/v1erNC0Hukz9nCBnN0ipHkHEGloZtIoiMGkkdTdE7sQPgFO5ePzh8nwPHMwI1BOAlnyK8DWAEtA0yDK2bE7imaUAiyIfKpL2+632nrm/M576DYNdwKkDSNj5yp3D23/6qnvT7gxPSGo/a59PNH0hwadiVVAP1N5YicvZKR8hqXjutTdUDjGQXB6mCLQDDZvHCplOf9K3IIdbxLVqwK80yGT2htiVEq/9BD93r0PSA9dnkrGxUj526/gZlGPqY9mNuZ4aQ==
  template:
    metadata:
      creationTimestamp: null
      name: ttaproxy-htpasswd
      namespace: monitoring
    type: Opaque
