apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ingatlan-api-secrets
  namespace: ingatlan
spec:
  encryptedData:
    JWT_SECRET: AgAR1SZFATundWrkc7a3mWcrWpzpHpyyutKvWk1FhSCq5EDIGciNt3z28XFk1by5RwDFdyhCfBShkbeY5d7kP70ijN6TW+5rdTqzKl1d1rzhdXWLw5DCrndpD1WdPe9MXBOovAMxzHprI6myLX5sbWYgRlVDMGXZ/Up25mk4Vcxr4yR+GvDo1XiCOX28iYVb1VU+CHS1c+MMNvF13l3PGTMktmk0pI0cupRKsPEf4kImc0gaKb3XNTTO8Dz6pZM0AMaHDJY+HueVuXr8KZogL9+AiNLchuAdWO9+UM78JCkWd8meErkC0YFSJx/2lXk64vyGKJAnrFGrepqQVUiPZr3dGVFRdGSZ+7rDM4X3uD8jKtibhfdQsqBvyvybEbJ/umohTMWmKuZVVBffubhmUtOxMDZiLl7Qgn2Zd3jk5pmOGIyUkwtNwozYSqRAwgAhStq4emwwrUqqYaDOHoy6okCisUcN+LfMsmXQ6VEFxKYeKRHs6pqE2IzQK9M7DVjdLoCnUNyay5zQXg+QEWVSedvEmTChI9qXQdkr62Vci2of04POUIN7oJyiTAXumn9Lh1HCHna1HFhvQS5i5W8oENaK9I8Wjure462mz019UgOB6zVIeOXNvfgQaAiWRKirQNdKTWh93cuU8BMYzQ7Z3E4InCsT9Qhkl7Ecx4yH6UatQXJbQEBJHZXC6whixIqPQz8QGEyVTn9ZN2D7hq6nxfEWpos02e/JnzsOb8PrS9KmT5jp7FlzN9R2wIWKuJUyvZEyCkEyxKimL20pldCO9gEZEYM=
    TELEGRAM_SECRET: AgCIGjgDftBjjzyVhhtpHWvESt0KTTcM+oFc6g/kdScerGR/3VsixUx+e70iMWvaQD8HKz9iR7A7IWKKEiFns8jIR5IBXJ5jeZhCyo118HQ9L98Mp8uBk47RhxBoBE/x0qNUZY8FtWSDY3FcKUxKYawZd9Z6tjKlQvF9t5y/ymuhfh2dfJ/+GyM+ZL5KB6JakY7tKF2kkNQnnmaF6I50MWwRkm2Tn/qAXueDzOgedpZcGiPeUS+6+d/dWhhuJOtPPxTFftq634rA9RF2OV5KujsPUX/rZsFHQp9FE8BQPG/qxUDR/7rtAk3OanaEInMqQmKgVZptbg+G1icCRCdWqHMYAFVmDbTNmE875oqWogxBcSyO2N5EagDuISXUsGn/3nFsClZsnk0ExJUZ4t7eODz6mCzRIuh/kFQWNnuUf0qSrCjMK1kI+ykEnpaqr3McoKce4UqUXIpbdCodAdm6TUX14zYKdI2PxOamc1nvK7cZv3pi89LkeGwoemyK5/cU/Jpt+PBKVmWivLiLHE5QUrp8+YZVN4vVIvaQwBg+L+FmRbrd1NfAOyHgiqZb+XqT3sn7o1/xnb5GGqmPDxPnGQM+nYFYVuo18zB1zNAnyM0Qahm4imKMNXxj5J49Qhd+u8Z16bXwDnPZoWqI1pdKdHUKR1lMmOO6sVtlhFCYb8VWhoKiatnWJjQGk3tTQGQRkIake2qGDIsIFZ2euDs+nXbPDuWIUZlbidYuq1eqdsBR2LKV+RKXcFB8/rkwPzwC6wgAKa1YFlWfGR8ov0q/7wS7
  template:
    metadata:
      creationTimestamp: null
      name: ingatlan-api-secrets
      namespace: ingatlan
    type: Opaque
