apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ingatlan-telegram-bot-secrets
  namespace: ingatlan
spec:
  encryptedData:
    MAPS_APIKEY: AgAsF8GwzkjuTNGZSGEWaHyT3tyQYUhBOd2BVbRA29stKK4gsck0MNtmauleINCH8Yr5KMp6pknX3efS2d+3AVOG04wwSi3Sq0O+D/Av7YlWZoJTMtLJSllwXHW27qKEJpTtrKM2PRPPXFHriD4kMZEUHk5wl4ftL/LIpd5hAuOhGazIfar8pjrLk8h1ms1B6dV4NUuugXG0vvxqFPS/vKA3xVE+ishTXmbe5An/RQExbPhfM2Qh51+Nc2FUejn6DUsYEe6JyCUKXisDte+iB1CkRIZDPRgNe7XtbfV71Y10V4tCpcigreT9OXimLxDCey48vR2x83rTC68vtDDz8i1RhTGRqQD/Te66qlhofywEkfUyvu9+fFzxkXt/zx+gVma5xEL8NOSDk8wbV4WMTfWviR0AJxyBAeo5LjQin4OcucDiP/GtX18SPCEn2OdLC4qR5o504uR1cWADy5u46AZVhXGoRbDNDKB4ks4kuM2LAYHNhJJaubQvxKp8cYkQSncvA5IOIKb7vpn3wbZX4Qi5mKYF5OZ9oHGjQ18Pb91eGcgvbKz4AEsenT2K2pl6O1ESrsGOFjS4LFZxyjmir5QQKxuVRFkvpLDyYEqmm/Tojrz4CxhrnEA6H8BiSQH6AICGpnMmIEUpOwI5B3DeBrmwWsajwZNVYafwEcy3QqKGxGsSi3vcJA6Brizt4g9EpmPSW3I=
    TELEGRAM_TOKEN: AgB/zYPOCbrtHn5ABN2/XRf0I3i1fCja3Z3Tj3Rh30kcZQcvC5H46yUSh5no54VJWfNLFdfBWRvr0jJNZhYKfpCWkufW9yehqc039f1hn4HWqi9uGAtvGj4dtREuzEfNwug5W4Tdf15XCA+N6gIckIjE44xPteFI9ZtgzXFGF5PDPXeFYlkRhvOyxZvHjKnEub4hwZaLn2O9Dz+8Ugw6N5HjyLMngVCcazN+/1tXxfmIhJ+sVyhDsb0qX85xu2FGtZmp7clxKehypZ34mAUpbeb/zOw9rO1S3fpNYEJ0k2gmNlxvjZ6So0sz+As9PVLPPy+oUPGXYkIOZaD/pEsrxQKCgZ5pxx+5iMT73+GJrjOphHlY2U2NGLprRGOhax1rXlK4eD72DGF8CH5AuO8crnx44gL7NTbBoNscrv6DSn11D7tGgvL5kBtaT2VcxCl/xUV7Fxy1YEYu4wPF0C9pDFVpRBpudJaPSEtEJgPqJoayakBNU0NMwBThLk6ysuJj9QjDiPcJYx5uNevmK3Mv2hioPzppDF49FO1eHSHnHswOM0z8qygVRCEOq9mQ0j87XkTiuO4y6bYS76FFcJcg4eW55azKR7vuAUanR58B+/m74H/44mDacNkH5Bc8wPUnpnOgiZPjrT4DZzjWRl0RZoP2gQOhmE0WrI8dv3YFHrjNRbGUtgtB4+7iknpra20OodEhNb/SUXb5OwgOgDy9w7xYwxVzdim3JXnFqTUa7k7IhF2aSdttr6dlUXdjKFc=
  template:
    metadata:
      creationTimestamp: null
      name: ingatlan-telegram-bot-secrets
      namespace: ingatlan
    type: Opaque
