apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: marcsellocorp-bot-secrets
  namespace: marcsellocorp-bot
spec:
  encryptedData:
    DATABASE_URL: AgCDp8ZZCGosag+Sq1JePvK5nQYOC+GKm5/bbV0pweS9ab10j0h3yVSVFTYTq3KaiVSziJxj2VrcE6TWE9+3c9j4cJ/57jgsrDOiz5OVWs/Lzn9KxPuJ0IAJp6OTMBcoAk/uq8lzPiYnqH0DZ80sH9mJbXiGB9C0j6XxFpChG9PiSF/9rWyS/g9XirCXdUu3Qx1jTZNKEkfgFKGK7E2B9bKv2MI64+iC6pIdtL4Xry74/b7nQ3QJoB1kxXEtm5NklYI77AO6EjlLPcYapToy/dFANQejB2pBheW81enO9UqUHkHkOXNAYOtFG/fsB2K3Vte633XGn/CF+REn2e89TtYq8RtxmWIWJBKpCQHudckchF69lb1yr5o/SYTOQ5GDSbCX+rBEL7QY574h3jgIdw9NzKVonrCURPnArVAsvdkBsCHXdOlyx41htP4TmbntbQfmwTpQ9D5UyRjNdG8Qr771XFEotfAuJI0sre1278vAOcojfkoUF5SKLqaeovyYStXuT4tvDyN5en2uerUYpwAKOgekDcm9+Eg7jeeQv+ZxV3ccdL4z0l9a6lLem7IcDxdmlE/bGIa9/+V40oQLgNe90Bf6yGvtqRuCxBIbYCj4fm6TUHNc8hCuDyoIqzCskTFL9v09VfNPrjFttq1dT8b0np1GLRjRB/ej0pJg6dU+p98h7oTyKijvrfp4HFe97TkmUKDgoJvIVtdt7zNvV5LHHbmNQPF9NfwFaeNigN/xkuSCniglE7NYzG9Q6fklgJuMvzExg9RB8Dbjt87lKstJDQYkz6S8v+DjrSRoax9qzzOtTmsBUh2DXqyM
    TELEGRAM_TOKEN: AgAkBAWaPT9FovyqFvz5VcwQqT4e5JfTNI/ltjUYHEJZfrdAUpMkEDoQBWQK/j2OXkGucC3DWtjxjxBvLPKPCg4CWIXVRs9b+WaLhgC1Q7+ITsPmkDSKuhhNAHgG25DdcV8X86fYXUtD2w9k/HY+MWA7+mXQeu95weow00cu3Qoh8FUyCEI7hGM3tEYrpyzXF9T4BpJoXn4+8zBoiPhfJ1LoJJj9H3ecEPOECsp2dESxZcIiHVs4y+6V7Gxdffi5D3R5HXvTRouoxDrmX8gJUMwNSHCCCXKHFrxckPH68h9bcWZVu0E84tOd3JkP6U39ruWPTSZORCFlS3asIG1Xz+V3QlJ15DRh6LVsKJn+q7LANlhAz5Ody5I9Y62jA/3tWTLH0vukUnO0CASck3DQ+ail00W/Ss136x4h+dg+JvGfTnDqzkrYXXByxQotTTTjQg3ZCZ4CPInTf9c3VLo9gbq5uJ7RiLjRHzLmTrMhsIPFeLFA67wI9RX7VtZAMQIxAtBTdM/T/VnxKtd1jzD7h5xFcpWlJSOnYCXrow1ZGUbUuf+4LDaD/Yk9EGWex3rEEQbeeGZm4ogRx46wI2YEsF4rq9KxDKoSvSI/y/JfbaRB1uu0dNqOu9T0V5Z33klcrEyOU0hqtUUHjLgUv3jzHvMpHBMeuN3KJzrGNC8C+ytaZslMuR38hxhnzJlAowHeL3Eao9oDOTwBYSyjfcQTR+rADB9hYQloaleV6tT3vRoukRDutjWyCQdwX1CLg4k=
  template:
    metadata:
      creationTimestamp: null
      name: marcsellocorp-bot-secrets
      namespace: marcsellocorp-bot
    type: Opaque
